# Generated by Django 5.0.6 on 2024-06-25 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technology',
            new_name='Skill',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='technologies',
            new_name='skill',
        ),
    ]
